BestJob/BestJob/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from news.views import IndexView
from search.views import CVSearchView, VacancySearchView, StandardSearch

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('news/', include('news.urls', namespace='news')),
    path('users/', include('users.urls', namespace='users')),
    path('cvs/', include('cvs.urls', namespace='cvs')),
    path('vacancies/', include('vacancies.urls', namespace='vacancies')),
    # path('search/', include('haystack.urls')),
    path('search/', StandardSearch(), name="haystack_search"),
    path('search_cv/', CVSearchView.as_view(), name='search_cv'),
    path('search_vacancy/', VacancySearchView.as_view(), name='search_vacancy'),
    path('relations/', include('relations.urls', namespace='relations')),
    path('favorites/', include('favorites.urls', namespace='favorites')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BestJob/cvs/urls.py
from django.urls import path

from cvs.views import CVList, CVCreate, CVUpdate, CVDelete, set_public_status, CVExperienceCreate, CVExperienceUpdate, \
    CVExperienceDelete, CVEducationCreate, CVEducationUpdate, CVEducationDelete, CVLanguageCreate, CVLanguageUpdate, \
    CVLanguageDelete, ModeratorCVList, ModeratorCVUpdate, CVDetailView, edit_cv_list, RecomendedCVList

app_name = 'cv'

urlpatterns = [
    path('all/', CVList.as_view(), name='cv_list'),
    path('create/', CVCreate.as_view(), name='create_cv'),
    path('update/<int:pk>/', CVUpdate.as_view(), name='update_cv'),
    path('delete/<int:pk>/', CVDelete.as_view(), name='delete_cv'),
    path('detail/<int:pk>/', CVDetailView.as_view(), name='detail_cv'),
    path('distribute/<int:pk>/', set_public_status, name='distribute_cv'),
    path('create_experience/<int:pk>', CVExperienceCreate.as_view(), name='create_experience'), # здесь pk - это cv.id
    path('update_experience/<int:pk>/', CVExperienceUpdate.as_view(), name='update_experience'), # а здесь pk - это experience.id
    path('delete_experience/<int:pk>/', CVExperienceDelete.as_view(), name='delete_experience'),
    path('create_education/<int:cv_id>/', CVEducationCreate.as_view(), name='create_education'),
    path('update_education/<int:pk>/', CVEducationUpdate.as_view(), name='update_education'),
    path('delete_education/<int:pk>/', CVEducationDelete.as_view(), name='delete_education'),
    path('create_language/<int:cv_id>/', CVLanguageCreate.as_view(), name='create_language'),
    path('update_language/<int:pk>/', CVLanguageUpdate.as_view(), name='update_language'),
    path('delete_language/<int:pk>/', CVLanguageDelete.as_view(), name='delete_language'),
    path('moderator_cvs/', ModeratorCVList.as_view(), name='moderator_cvs_list'),
    path('moderator_cvs_approve/<int:pk>/', ModeratorCVUpdate.as_view(), name='moderator_cvs_approve'),
    path('edit_cv_list/<str:stat>/', edit_cv_list, name='edit_cv_list'),
    path('cv_recommended/<int:pk>/', RecomendedCVList.as_view(), name='cv_recommended'),

]

BestJob/vacancies/urls.py
from django.urls import path


from news.views import NewsCreate, NewsUpdate, NewsDelete, NewsModerateList

from vacancies.views import VacancyList, VacancyCreate, VacancyUpdate, VacancyDelete, \
    VacancyDistribute, ModeratorVacancyList, ModeratorVacancyUpdate, \
    VacancyDetail, VacancyOpenList, RecommendedVacancyList, edit_vacancy_list, set_public_status

app_name = 'vacancy'

urlpatterns = [
    path('all/', VacancyList.as_view(), name='vacancy_list'),
    path('create/', VacancyCreate.as_view(), name='create_vacancy'),
    path('update/<int:pk>/', VacancyUpdate.as_view(), name='update_vacancy'),
    path('delete/<int:pk>/', VacancyDelete.as_view(), name='delete_vacancy'),
    path('distribute/<int:pk>/', set_public_status, name='distribute_vacancy'),
    # просмотр всех вакансий любым пользователем
    path('all/open/', VacancyOpenList.as_view(), name='vacancy_openlist'),
    # просмотр вакансий рекомендованных по конкретному резюме
    path('recommended/<int:pk>/', RecommendedVacancyList.as_view(), name='vacancy_recommended'),
    path('moderator_vacancy/', ModeratorVacancyList.as_view(), name='moderator_vacancy_list'),
    path('moderator_vacancy_approve/<int:pk>/', ModeratorVacancyUpdate.as_view(), name='moderator_vacancy_approve'),
    path('detail/<int:pk>/', VacancyDetail.as_view(), name='detail_vacancy'),
    # обновление списка вакансий у модератора по статусу
    path('edit_vacancy_list/<str:stat>/', edit_vacancy_list, name='edit_vacancy_list' ),

]

BestJob/search/models.py
from django.db import models

# Create your models here.

class EducationLevel(models.IntegerChoices):
    """Уровень образования (выбор одного значения)"""
    SECONDARY = 1, "Среднее"
    SPEC_SEC = 2, "Среднее специальное"
    INC_HIGHER = 3, "Неоконченное высшее"
    HIGHER = 4, "Высшее"
    BACHELOR = 5, "Бакалавр"
    MASTER = 6, "Магистр"
    CANDIDATE = 7, "Кандидат наук"
    DOCTOR = 8, "Доктор наук"


class Moving(models.IntegerChoices):
    """Переезд (выбор одного значения)"""
    UNREAL = 1, "Невозможен"
    REAL = 2, "Возможен"
    DESIRE = 3, "Желателен"


class MainSkills(models.Model):
    """Ключевые навыки. code: DJANGO, skill: Django Framework"""
    code = models.CharField(max_length=10, unique=True)
    skill = models.CharField(max_length=100, unique=True)


class Languages(models.Model):
    """Языки. code: ENG, language: английский"""
    code = models.CharField(max_length=3, unique=True)
    language = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.language

class LanguageLevels(models.Model):
    """Уровень владения языком. code: A1, level: Начальный"""
    code = models.CharField(max_length=3, unique=True)
    level = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.level


class Employments(models.Model):
    """Занятость. code: FULL, employment: Полная занятость"""
    code = models.CharField(max_length=10, unique=True)
    employment = models.CharField(max_length=100, unique=True)


class WorkSchedules(models.Model):
    """График работы. code: FULL, schedule: Полный день"""
    code = models.CharField(max_length=10, unique=True)
    schedule = models.CharField(max_length=100, unique=True)


class Category(models.Model):
    """Специализации. code: PROG, name: Программист"""
    code = models.CharField(max_length=10, unique=True)
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name


class Currency(models.IntegerChoices):
    """Валюта (выбор одного значения)"""
    RUB = 1, 'Рубли'
    USD = 2, 'Доллары, США'
    EUR = 3, 'Евро'
    KZT = 4, 'Тенге, Казахстан'

BestJob/search/views.py
from django.contrib import messages
from haystack.generic_views import SearchView
from haystack.views import SearchView as SearchViewStandard
from haystack.query import SearchQuerySet

from BestJob.mixin import FavouriteListMixin
from cvs.models import CV
from search.form import CVSearchForm, VacancySearchForm
from vacancies.models import Vacancy
from BestJob.settings import UserRole


class StandardSearch(SearchViewStandard, FavouriteListMixin):
    def extra_context(self):
        """
        Allows the addition of more context variables as needed.

        Must return a dictionary.
        """
        return {'favourite_list': self.get_favourite_list()}

class CVSearchView(SearchView, FavouriteListMixin):
    """My custom search view."""
    template_name = 'search/search_cv.html'
    queryset = SearchQuerySet().all()
    form_class = CVSearchForm
    model = CV
    paginate_by = 2

    def get_context_data(self, *args, **kwargs):
        context = super(CVSearchView, self).get_context_data(**kwargs)
        if self.request.user.id is None or self.request.user.role.id == UserRole.WORKER:
            context['message_of_denied'] = 'Просматривать резюме могут только авторизованные ' \
                                           'работодатели!'
        context['title'] = "Поиск резюме"
        context['heading'] = "Поиск резюме"
        return context


class VacancySearchView(SearchView, FavouriteListMixin):
    """My custom search view."""
    template_name = 'search/search_vacancy.html'
    queryset = SearchQuerySet().all()
    form_class = VacancySearchForm
    model = Vacancy
    paginate_by = 2

    def get_context_data(self, *args, **kwargs):
        context = super(VacancySearchView, self).get_context_data(**kwargs)
        if self.request.user.id is None or self.request.user.role.id == UserRole.EMPLOYER:
            context['message_of_denied'] = 'Просматривать вакансии могут только авторизованные ' \
                                           'соискатели!'
        context['title'] = "Поиск вакансий"
        context['heading'] = "Поиск вакансий"
        return context

BestJob/templates/search/search_old.html
{% extends 'base.html' %}

{% load static %}

{% block menu %}
    {% include 'inc_main_menu.html' %}
{% endblock %}

{% block search %}
    <section class="overlay-black">
        <div class="container wrapper">
            <br>
            <h1 class="capitalize text-center text-white">Поиск</h1>
            <form method="get" action="." class="job-search-form row pt40 center ">

                <div class="col-md-5 col-sm-12 search-keywords">
                    {{ form.q }}
                </div>

                <div class="col-md-3 col-sm-12 search-submit">
                    <input type="submit" value="найти" class="btn btn-blue btn-effect btn-large">
                </div>


                <div class="col-md-4 col-sm-12 ">
                    <a href="{% url 'search_vacancy' %}" class="capitalize text-white">расширенный поиск
                        вакансий</a>
                    <br>
                    <a href="{% url 'search_cv' %}" class="capitalize  text-white">расширенный поиск резюме</a>
                </div>
            </form>

        </div>
        <br>
    </section>
{% endblock %}

{% block footer %}
    {% include 'inc_footer.html' %}
{% endblock %}

{% block content %}
    <section class="education ptb80 " style="background-color: rgba(41, 177, 253, 0.25)">

        <div class="container">
            {% if query %}
                {% for result in page.object_list %}
                    {% if result.object.post %}

                            <div class="col-md-12" style="margin-bottom: 15px;">
                                <div class="item-block shadow-hover" style="background: #ffffff;">

                                    <div class="education-header clearfix">
                                        <div style="margin-bottom: 15px; border-bottom: 1px solid #e3e3e3; width: 100%">
                                            Резюме
                                        </div>
                                        <br>
                                        <a href="{% url 'cv:detail_cv' result.object.id %}"  >
                                        <div style="margin-bottom: 15px;"><h4>{{ result.object.post }}</h4></div>
                                        </a>
                                            <br>
                                        <div><h6>{{ result.object.salary }} RUB</h6></div>
                                        <a href="#" style="color: lightgray">
                                            <div class="pull-right"><h3>★</h3></div>
                                        </a>
                                    </div>
                                </div>
                            </div>

                    {% endif %}
                    {% if result.object.name %}

                        <div class="col-md-12" style="margin-bottom: 15px;">
                            <div class="item-block shadow-hover " style="background: #ffffff;">

                                <div class="education-header clearfix">
                                    <div style="margin-bottom: 15px; border-bottom: 1px solid #e3e3e3; width: 100%">
                                        Вакансия
                                    </div>
                                    <br>
                                    <a href="{% url 'vacancy:detail_vacancy' result.object.id %}"
                                       >
                                        <div style="margin-bottom: 15px;"><h4>{{ result.object.name }}</h4></div>
                                    </a>
                                    <br>
                                    <div><h6>{{ result.object.salary_from }} - {{ result.object.salary_to }}
                                        RUB</h6></div>

                                    <a href="#" style="color: lightgray">
                                        <div class="pull-right"><h3>★</h3></div>
                                    </a>
                                </div>
                            </div>
                        </div>

                    {% endif %}



                {% empty %}
                    <p>Ничего не найдено...</p>
                {% endfor %}


                {% if page.has_previous or page.has_next %}
                    <div>
                        {% if page.has_previous %}
                            <a href="?q={{ query }}&amp;page={{ page.previous_page_number }}">{% endif %}&laquo;
                        Previous
                        {% if page.has_previous %}</a>{% endif %}
                        |
                        {% if page.has_next %}<a href="?q={{ query }}&amp;page={{ page.next_page_number }}">{% endif %}
                        Next
                        &raquo;{% if page.has_next %}</a>{% endif %}
                    </div>
                {% endif %}
            {% else %}
                {# Show some example queries to run, maybe query syntax, something else? #}
            {% endif %}

            {##}
            {#        <div class="container wrapper ">#}
            {#            {% if query %}#}
            {#                <br>#}
            {#                <table width="100%">#}
            {#                    <tr>#}
            {#                        <th>Тип</th>#}
            {#                        <th>Название</th>#}
            {#                        <th>Оклад</th>#}
            {#                    </tr>#}
            {#                    {% for result in page.object_list %}#}
            {#                        {% if result.object.post %}#}
            {#                            <tr>#}
            {#                                <td> Резюме</td>#}
            {#                                <td><a href="{% url 'cv:update_cv' result.object.id %}">#}
            {#                                    {{ result.object.post }}</a></td>#}
            {#                                <td>{{ result.object.salary }}</td>#}
            {#                            </tr>#}
            {#                        {% endif %}#}
            {#                        {% if result.object.name %}#}
            {#                            <tr>#}
            {#                                <td> Вакансия</td>#}
            {#                                <td>#}
            {#                                    <a href="{% url 'vacancy:detail_vacancy' result.object.id %} "#}
            {#                                    >#}
            {#                                        {{ result.object.name }}</a>#}
            {#                                </td>#}
            {#                                <td>{{ result.object.salary_from }} - {{ result.object.salary_to }}</td>#}
            {#                            </tr>#}
            {#                        {% endif %}#}
            {##}
            {##}
            {##}
            {#                    {% empty %}#}
            {#                        <p>No results found.</p>#}
            {#                    {% endfor %}#}
            {#                </table>#}
            {##}
            {#                {% if page.has_previous or page.has_next %}#}
            {#                    <div>#}
            {#                        {% if page.has_previous %}#}
            {#                            <a href="?q={{ query }}&amp;page={{ page.previous_page_number }}">{% endif %}&laquo;#}
            {#                        Previous#}
            {#                        {% if page.has_previous %}</a>{% endif %}#}
            {#                        |#}
            {#                        {% if page.has_next %}<a href="?q={{ query }}&amp;page={{ page.next_page_number }}">{% endif %}#}
            {#                        Next#}
            {#                        &raquo;{% if page.has_next %}</a>{% endif %}#}
            {#                    </div>#}
            {#                {% endif %}#}
            {#            {% else %}#}
            {# Show some example queries to run, maybe query syntax, something else? #}
            {#            {% endif %}#}
            <br>
        </div>
    </section>
{% endblock %}