BestJob/BestJob/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from news.views import IndexView
from search.views import CVSearchView, VacancySearchView, StandardSearch

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('news/', include('news.urls', namespace='news')),
    path('users/', include('users.urls', namespace='users')),
    path('cvs/', include('cvs.urls', namespace='cvs')),
    path('vacancies/', include('vacancies.urls', namespace='vacancies')),
    # path('search/', include('haystack.urls')),
    path('search/', StandardSearch(), name="haystack_search"),
    path('search_cv/', CVSearchView.as_view(), name='search_cv'),
    path('search_vacancy/', VacancySearchView.as_view(), name='search_vacancy'),
    path('relations/', include('relations.urls', namespace='relations')),
    path('favorites/', include('favorites.urls', namespace='favorites')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BestJob/cvs/urls.py
from django.urls import path

from cvs.views import CVList, CVCreate, CVUpdate, CVDelete, set_public_status, CVExperienceCreate, CVExperienceUpdate, \
    CVExperienceDelete, CVEducationCreate, CVEducationUpdate, CVEducationDelete, CVLanguageCreate, CVLanguageUpdate, \
    CVLanguageDelete, ModeratorCVList, ModeratorCVUpdate, CVDetailView, edit_cv_list, RecomendedCVList

app_name = 'cv'

urlpatterns = [
    path('all/', CVList.as_view(), name='cv_list'),
    path('create/', CVCreate.as_view(), name='create_cv'),
    path('update/<int:pk>/', CVUpdate.as_view(), name='update_cv'),
    path('delete/<int:pk>/', CVDelete.as_view(), name='delete_cv'),
    path('detail/<int:pk>/', CVDetailView.as_view(), name='detail_cv'),
    path('distribute/<int:pk>/', set_public_status, name='distribute_cv'),
    path('create_experience/<int:pk>', CVExperienceCreate.as_view(), name='create_experience'), # здесь pk - это cv.id
    path('update_experience/<int:pk>/', CVExperienceUpdate.as_view(), name='update_experience'), # а здесь pk - это experience.id
    path('delete_experience/<int:pk>/', CVExperienceDelete.as_view(), name='delete_experience'),
    path('create_education/<int:cv_id>/', CVEducationCreate.as_view(), name='create_education'),
    path('update_education/<int:pk>/', CVEducationUpdate.as_view(), name='update_education'),
    path('delete_education/<int:pk>/', CVEducationDelete.as_view(), name='delete_education'),
    path('create_language/<int:cv_id>/', CVLanguageCreate.as_view(), name='create_language'),
    path('update_language/<int:pk>/', CVLanguageUpdate.as_view(), name='update_language'),
    path('delete_language/<int:pk>/', CVLanguageDelete.as_view(), name='delete_language'),
    path('moderator_cvs/', ModeratorCVList.as_view(), name='moderator_cvs_list'),
    path('moderator_cvs_approve/<int:pk>/', ModeratorCVUpdate.as_view(), name='moderator_cvs_approve'),
    path('edit_cv_list/<str:stat>/', edit_cv_list, name='edit_cv_list'),
    path('cv_recommended/<int:pk>/', RecomendedCVList.as_view(), name='cv_recommended'),

]

BestJob/favorites/urls.py
from django.template.defaulttags import url
from django.urls import path, re_path

from .views import FavoritesWorkerListView, FavoritesEmployerListView, FavoritesWorkerDeleteView, \
    FavoritesEmployerDeleteView, fav_emp_add_remove, fav_work_add_remove

app_name = 'favorites'

urlpatterns = [

    # оставил себе регулярку, как передать url(link) в параметре c клиента.
    # re_path(r'^employer_add/(?P<cv_id>\d+)/(?P<search_url>[\w|\W]+)/$', fav_emp_create, name='employer_add'),
    # re_path(r'^worker_add/(?P<vacancy_id>\d+)/(?P<search_url>[\w|\W]+)/$', fav_work_create, name='worker_add'),

    path('employer_add_remove/<int:cv_id>/', fav_emp_add_remove, name='employer_add_remove'),
    path('worker_add_remove/<int:vacancy_id>/', fav_work_add_remove, name='worker_add_remove'),

    path('worker_delete/<int:pk>/', FavoritesWorkerDeleteView.as_view(), name='worker_delete'),
    path('employer_delete/<int:pk>/', FavoritesEmployerDeleteView.as_view(), name='employer_delete'),
    path('worker_list/', FavoritesWorkerListView.as_view(), name='worker_list'),
    path('employer_list/', FavoritesEmployerListView.as_view(), name='employer_list'),
]

BestJob/relations/urls.py
from django.urls import path, re_path

from .views import RelationListView, RelationDetailView, RelationCreateFromFavoritesView, \
    RelationCreateFromRelationView, RelationCreateFromRelationDetailView

app_name = 'relations'

urlpatterns = [
    path('list/', RelationListView.as_view(), name='list'),
    path('detail/<int:relation_id>/', RelationDetailView.as_view(), name='detail'),
    # Создание из favorites
    re_path(r'^create_from_fav/(?P<magic_id>\d+)/(?P<select_picker_id>\d+)/(?P<letter>[\w|\W]+)/$',
            RelationCreateFromFavoritesView.as_view(), name='create_from_fav'),
    # Создание из relation
    re_path(r'^create_from_rel/(?P<magic_id>\d+)/(?P<select_picker_id>\d+)/(?P<letter>[\w|\W]+)/$',
            RelationCreateFromRelationView.as_view(), name='create_from_rel'),
    # Создание из relation detail
    re_path(r'^create_from_detail/(?P<magic_id>\d+)/(?P<select_picker_id>\d+)/(?P<letter>[\w|\W]+)/$',
            RelationCreateFromRelationDetailView.as_view(), name='create_from_detail'),
]

BestJob/vacancies/urls.py
from django.urls import path


from news.views import NewsCreate, NewsUpdate, NewsDelete, NewsModerateList

from vacancies.views import VacancyList, VacancyCreate, VacancyUpdate, VacancyDelete, \
    VacancyDistribute, ModeratorVacancyList, ModeratorVacancyUpdate, \
    VacancyDetail, VacancyOpenList, RecommendedVacancyList, edit_vacancy_list, set_public_status

app_name = 'vacancy'

urlpatterns = [
    path('all/', VacancyList.as_view(), name='vacancy_list'),
    path('create/', VacancyCreate.as_view(), name='create_vacancy'),
    path('update/<int:pk>/', VacancyUpdate.as_view(), name='update_vacancy'),
    path('delete/<int:pk>/', VacancyDelete.as_view(), name='delete_vacancy'),
    path('distribute/<int:pk>/', set_public_status, name='distribute_vacancy'),
    # просмотр всех вакансий любым пользователем
    path('all/open/', VacancyOpenList.as_view(), name='vacancy_openlist'),
    # просмотр вакансий рекомендованных по конкретному резюме
    path('recommended/<int:pk>/', RecommendedVacancyList.as_view(), name='vacancy_recommended'),
    path('moderator_vacancy/', ModeratorVacancyList.as_view(), name='moderator_vacancy_list'),
    path('moderator_vacancy_approve/<int:pk>/', ModeratorVacancyUpdate.as_view(), name='moderator_vacancy_approve'),
    path('detail/<int:pk>/', VacancyDetail.as_view(), name='detail_vacancy'),
    # обновление списка вакансий у модератора по статусу
    path('edit_vacancy_list/<str:stat>/', edit_vacancy_list, name='edit_vacancy_list' ),

]

BestJob/cvs/models.py
from django.db import models

# Create your models here.
from approvals.models import ApprovalStatus
from search.models import Languages, LanguageLevels, Employments, WorkSchedules, MainSkills, Moving, EducationLevel, Category, Currency
from users.models import WorkerProfile, EmployerProfile
from vacancies.models import Vacancy


class CV(models.Model):
    """Резюме"""
    worker_profile = models.ForeignKey(WorkerProfile, on_delete=models.CASCADE, verbose_name='Профиль соискателя')
    status = models.ForeignKey(ApprovalStatus, on_delete=models.CASCADE, verbose_name='Статус')
    date_create = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    is_active = models.BooleanField(default=True, db_index=True, verbose_name='Активна?')
    speciality = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, blank=True, verbose_name='Специализация')
    post = models.CharField(max_length=256, blank=True, null=True, verbose_name='Название')
    skills = models.CharField(max_length=256, blank=True, null=True, verbose_name='Навыки')
    education_level = models.PositiveSmallIntegerField(choices=EducationLevel.choices, default=EducationLevel.HIGHER, verbose_name='Уровень образования')
    moving = models.PositiveSmallIntegerField(choices=Moving.choices, default=Moving.UNREAL, null=True, verbose_name='Готовность к переезду')
    salary = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, verbose_name='Зарплата')
    currency = models.PositiveSmallIntegerField(choices=Currency.choices, default=Currency.RUB, null=True, verbose_name='Валюта')
    about = models.TextField(max_length=5000, blank=True, null=True, verbose_name='Обо Мне')
    moderators_comment = models.TextField(max_length=5000,blank=True, null=True, verbose_name='Комментарий модератора')


class CVSkills(models.Model):
    """Ключевые навыки"""
    cv = models.ForeignKey(CV, on_delete=models.CASCADE)
    skill = models.ForeignKey(MainSkills, on_delete=models.CASCADE)


class Education(models.Model):
    """Образование"""
    cv = models.ForeignKey(CV, on_delete=models.CASCADE)
    date_end = models.IntegerField(null=True)
    name = models.CharField(max_length=256)
    department = models.CharField(max_length=256)
    specialty = models.CharField(max_length=256)


class CVMonths(models.IntegerChoices):
    JAN = 1, "Январь"
    FEB = 2, "Февраль"
    MAR = 3, "Март"
    APR = 4, "Апрель"
    MAY = 5, "Май"
    JUN = 6, "Июнь"
    JUL = 7, "Июль"
    AUG = 8, "Август"
    SEP = 9, "Сентябрь"
    OCT = 10, "Октябрь"
    NOV = 11, "Ноябрь"
    DEC = 12, "Декабрь"

class Experience(models.Model):

    cv = models.ForeignKey(CV, on_delete=models.CASCADE)
    month_begin = models.PositiveSmallIntegerField(choices=CVMonths.choices, default=CVMonths.JAN)
    year_begin = models.IntegerField(null=True)
    month_end = models.PositiveSmallIntegerField(choices=CVMonths.choices, default=CVMonths.JAN)
    year_end = models.IntegerField(null=True)
    name = models.CharField(max_length=256)
    post = models.CharField(max_length=128)
    stack = models.CharField(max_length=256, null=True)
    responsibilities = models.TextField(max_length=2000, null=True)


class LanguagesSpoken(models.Model):
    """Владение языками в резюме (возможно несколько значений)"""
    cv = models.ForeignKey(CV, on_delete=models.CASCADE)
    language = models.ForeignKey(Languages, on_delete=models.CASCADE)
    level = models.ForeignKey(LanguageLevels, on_delete=models.CASCADE)


class CVEmployment(models.Model):
    """Занятость в резюме (возможно несколько значений)"""
    cv = models.ForeignKey(CV, on_delete=models.CASCADE)
    employment = models.ForeignKey(Employments, on_delete=models.CASCADE)


class CVWorkSchedule(models.Model):
    """График работы в резюме (возможно несколько значений)"""
    cv = models.ForeignKey(CV, on_delete=models.CASCADE)
    schedule = models.ForeignKey(WorkSchedules, on_delete=models.CASCADE)


class SelectedCV(models.Model):
    """Избранные резюме"""
    cv = models.ForeignKey(CV, on_delete=models.CASCADE)
    employer_profile = models.ForeignKey(EmployerProfile, on_delete=models.CASCADE)

BestJob/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" style="height: 100%;">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,400i,700,800|Varela+Round"
          rel="stylesheet">

    <!-- favicon link -->
    <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.png' %}"/>

    <!-- CSS links -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-select.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/swiper.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/responsive.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap-datetimepicker.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap_datepicker_plus/css/datepicker-widget.css' %}">
    {% block additional_styles %}
    {% endblock %}
</head>

<body style="height: 100%; display: flex; flex-direction: column;">

<main style="flex: 1 0 auto;">

    {% block menu %}
    {% endblock %}

    {% block header %}
    {% endblock %}

    {% block search %}
    {% endblock %}

    {% block content %}
    {% endblock %}

</main>

{% block footer %}
{% endblock %}

<!-- ===== Start of Back to Top Button ===== -->
<a href="#" class="back-top"><i class="fa fa-chevron-up"></i></a>
<!-- ===== End of Back to Top Button ===== -->

<!-- ===== All Javascript at the bottom of the page for faster page loading ===== -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/bootstrap-select.min.js' %}"></script>
<script src="{% static 'js/swiper.min.js' %}"></script>
<script src="{% static 'js/jquery.ajaxchimp.js' %}"></script>
<script src="{% static 'js/jquery.countTo.js' %}"></script>
<script src="{% static 'js/jquery.inview.min.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/jquery.easypiechart.min.js' %}"></script>
<script src="{% static 'js/jquery-ui.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/tinymce/tinymce.min.js' %}"></script>
<script src="{% static 'js/isotope.min.js' %}"></script>
<script src="{% static 'js/custom.js' %}"></script>
<script src="{% static 'js/moderators_lists.js' %}"></script>

</body>
{% block additional_script %}
{% endblock %}
</html>

BestJob/templates/favorites_list.html
{% extends 'base.html' %}
{% load static %}

{% block additional_styles %}
    <meta name="csrf-token" content="{{ csrf_token }}">
{% endblock %}

{% block menu %}
    {% include 'inc_main_menu.html' %}
{% endblock %}

{% block header %}
    {% include 'inc_header_menu.html' %}
{% endblock %}

{% block content %}

    <section class="search-jobs ptb80" id="version4" style="background: #ffffff;">
        <div class="container">

            {% for item in page_obj %}

                <div class="col-md-12 mt20">
                    <div class="item-block shadow-hover">

                        {% if is_employer %}

                            <div class="job-post-header clearfix">
                                <a href="{% url 'cv:detail_cv' item.cv.pk %}"><img
                                        src="{{ item.cv.worker_profile.image.url }}" alt=""></a>
                                <div>
                                    <a href="{% url 'cv:detail_cv' item.cv.pk %}"><h4>{{ item.cv.post }}</h4></a>
                                    <h5><small>{{ item.cv.worker_profile.name }}</small></h5>
                                </div>

                                <ul class="pull-right">
                                    <li>
                                        <a href="{% url 'favorites:employer_delete' item.pk %}"
                                           class="btn btn-blue btn-small btn-effect">Убрать из избранного</a>

                                        {% if not item.has_relaton %}

                                            <span id="relation_btn_{{ item.cv.pk }}_{{ item.pk }}">
                                                <a id="employer_modal_trigger" href="#"
                                                   onclick="openModalForm({{ item.cv.pk }},{{ item.pk }})"
                                                   class="btn btn-blue btn-small btn-effect" role="button">Отправить приглашение</a>
                                            </span>

                                        {% endif %}
                                    </li>
                                    <li id="has_relaton_{{ item.cv.pk }}_{{ item.pk }}">
                                        {% if item.has_relaton == 1 %}

                                            <a href="{% url 'relations:detail' item.relations_id %}">
                                                <h6 class="time">У вас есть взаимодействия по этому резюме</h6></a>

                                        {% endif %}
                                    </li>
                                </ul>
                            </div>

                            <div class="job-post-body">
                                <ul class="list mt10">
                                    {% if item.cv.speciality.name %}
                                        <li>{{ item.cv.speciality.name }}</li>
                                    {% endif %}

                                    {% if item.cv.skills %}
                                        <li>{{ item.cv.skills }}</li>
                                    {% endif %}

                                    {% if item.cv.education_level >= 4 %}
                                        <li>Высшее</li>
                                    {% endif %}

                                    {% if item.cv.is_active %}
                                        <li>Резюме активно</li>
                                    {% else %}
                                        <li>Резюме неактивно</li>
                                    {% endif %}
                                </ul>
                            </div>

                            <div class="job-post-footer row">

                                {% if item.cv.worker_profile.city %}

                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <i class="fa fa-map-marker"></i>
                                        <span>{{ item.cv.worker_profile.city }}</span>
                                    </div>

                                {% endif %}

                                {% if item.cv.salary %}

                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <i class="fa fa-money"></i>
                                        <span>{{ item.cv.salary }}</span>
                                    </div>

                                {% endif %}
                            </div>

                        {% elif is_worker %}

                            <div class="job-post-header clearfix">
                                <a href="{% url 'vacancies:detail_vacancy' item.vacancy.pk %}"><img
                                        src="{{ item.vacancy.employer_profile.image.url }}" alt=""></a>
                                <div>
                                    <a href="{% url 'vacancies:detail_vacancy' item.vacancy.pk %}">
                                        <h4>{{ item.vacancy.name }}</h4>
                                    </a>
                                    <h5><small>{{ item.vacancy.employer_profile.name }}</small></h5>
                                </div>

                                <ul class="pull-right">
                                    <li>
                                        <a href="{% url 'favorites:worker_delete' item.pk %}"
                                           class="btn btn-blue btn-small btn-effect">Убрать из избранного</a>
                                        {% if not item.has_relaton %}

                                            <span id="relation_btn_{{ item.vacancy.pk }}_{{ item.pk }}">
                                                <a id="worker_modal_trigger" href="#"
                                                   onclick="openModalForm({{ item.vacancy.pk }},{{ item.pk }})"
                                                   class="btn btn-blue btn-small btn-effect" role="button">Отправить отклик</a>
                                            </span>

                                        {% endif %}
                                    </li>
                                    <li id="has_relaton_{{ item.vacancy.pk }}_{{ item.pk }}">
                                        {% if item.has_relaton %}

                                            <a href="{% url 'relations:detail' item.relations_id %}">
                                                <h6 class="time">У вас есть взаимодействия по этой вакансии</h6></a>

                                        {% endif %}
                                    </li>
                                </ul>

                            </div>

                            <div class="job-post-body">
                                <ul class="list mt10">

                                    {% if item.vacancy.specialization.name %}
                                        <li>{{ item.vacancy.specialization.name }}</li>
                                    {% endif %}

                                    {% if item.vacancy.description %}
                                        <li>{{ item.vacancy.description }}</li>
                                    {% endif %}

                                    {% if item.vacancy.is_active %}
                                        <li>Вакансия активна</li>
                                    {% else %}
                                        <li>Вакансия неактивна</li>
                                    {% endif %}

                                </ul>
                            </div>

                            <div class="job-post-footer row">

                                {% if item.vacancy.city %}

                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <i class="fa fa-map-marker"></i>
                                        <span>{{ item.vacancy.city }}</span>
                                    </div>

                                {% endif %}

                                {% if item.salary_from and item.salary_to %}

                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <i class="fa fa-money"></i>
                                        <span>{{ item.salary_from }} - {{ item.salary_to }}</span>
                                    </div>

                                {% elif item.salary_on_hand %}

                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <i class="fa fa-money"></i>
                                        <span>{{ item.salary_on_hand }}</span>
                                    </div>

                                {% endif %}

                            </div>

                        {% endif %}
                    </div>
                </div>

            {% endfor %}

            <div class="col-md-12">
                <ul class="pagination list-inline text-center">
                    {% if page_obj.has_previous %}
                        <li><a href="?page=1">&laquo; первая</a></li>
                        <li><a href="?page={{ page_obj.previous_page_number }}">предыдущая</a></li>

                    {% endif %}

                    <span class="current">
                                    Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
                                </span>

                    <li class="active"><a href="javascript:void(0)">{{ page_obj.number }}</a></li>

                    {% if page_obj.has_next %}

                        <li><a href="?page={{ page_obj.next_page_number }}">следующая</a></li>
                        <li><a href="?page={{ page_obj.paginator.num_pages }}">последняя &raquo;</a></li>
                    {% endif %}
                </ul>
            </div>

        </div>
    </section>

    {% include 'inc_favorites_list_relation_modal_form.html' %}

{% endblock %}

{% block footer %}
    {% include 'inc_footer.html' %}
{% endblock %}

{% block additional_script %}
    <script src="{% static 'js/favorites_list.js' %}"></script>
{% endblock %}

BestJob/templates/relation_last_list.html
{% extends 'base.html' %}
{% load static %}

{% block additional_styles %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/detail_last_list_section.css' %}">
    <meta name="csrf-token" content="{{ csrf_token }}">
{% endblock %}

{% block menu %}
    {% include 'inc_main_menu.html' %}
{% endblock %}

{% block header %}
    {% include 'inc_header_menu.html' %}
{% endblock %}

{% block content %}
    {% include 'inc_relation_last_list_section.html' %}
    {% include 'inc_relation_modal_form.html' %}
{% endblock %}

{% block footer %}
    {% include 'inc_footer.html' %}
{% endblock %}

{% block additional_script %}
   <script src="{% static 'js/relation.js' %}"></script>
{% endblock %}

BestJob/templates/vacancy_list.html
{% extends 'base.html' %}
{% load static %}

{% block menu %}
    {% include 'inc_main_menu.html' %}
{% endblock %}

{% block header %}
    {% include 'inc_header_menu.html' %}
{% endblock %}

{% block content %}

    {% block messages %}
        {% include 'inc_messages_for_forms.html' %}
    {% endblock %}

    <!--    Начало секции Вакансии-->
    <section class="education ptb80">
        <div class="container">

            {% for vacancy in  vacancies %}
                <div class="col-md-12" style="margin-bottom: 15px;">
                    <div class="item-block shadow-hover" style="background: #ffffff;">

                        <div class="education-header clearfix">
                            <div class="col-md-8 col-xs-6 ptb20">
                                <h5><small>Вакансия -</small><a
                                        href="{% url 'vacancies:detail_vacancy' vacancy.id %}">{{ vacancy.name }}</a>
                                </h5>
                                <h5><small>Работодатель -</small> {{ vacancy.employer_profile.name }} </h5>
                                <h5><small>Зарплата -</small>
                                    {% if vacancy.salary_from %}
                                        {{ vacancy.salary_from }}
                                    {% endif %}

                                    {% if vacancy.salary_from and vacancy.salary_to %}
                                        -
                                    {% endif %}

                                    {% if vacancy.salary_to %}
                                        {{ vacancy.salary_to }}
                                    {% endif %}</h5>
                                <h5><small>Дата создания -</small> {{ vacancy.created_at }} </h5>

                                {% if employer %}
                                    <h5><small>Статус вакансии -</small> {{ vacancy.status }} </h5>
                                    {% if vacancy.status.code == 'FRV' %}
                                        <p style="color:#ff0000;">Внимание! Модератор отправил вакансию на доработку!
                                            {% if vacancy.moderators_comment %}
                                                <p style="color:#ff0000;">Прочесть комментарии модератора можно на форме
                                                    редактирования.</p>
                                            {% endif %}
                                    {% elif vacancy.status.code == 'RJC' %}
                                        <p style="color:#ff0000;">Внимание! Вакансия отклонена модератором!
                                            {% if vacancy.moderators_comment %}
                                                <p style="color:#ff0000;">Прочесть комментарии модератора можно на форме
                                                    редактирования.</p>
                                            {% endif %}
                                    {% endif %}

                                {% endif %}
                            </div>
                            <div class="col-md-2 col-xs-3 ptb20">
                                <div class="candidate-cta ptb30">
                                    {% load extra_tags %}
                                    {% if worker %}
                                        {% is_workers_favorite vacancy.id worker.id as favorite %}
                                        {% if favorite %}
                                            <a href="{% url 'favorites:worker_add_remove' vacancy_id=vacancy.id %}"
                                               style="color: orange">
                                            <div data-toggle="tooltip" data-placement="bottom"
                                                 title="Уже у Вас в избранном" class="pull-right">
                                                <h3>★</h3>
                                            </div>
                                            </a>
                                        {% else %}
                                            <a href="{% url 'favorites:worker_add_remove' vacancy_id=vacancy.id %}"
                                               style="color: lightgray">
                                                <div class="pull-right"><h3>★</h3></div>
                                            </a>
                                        {% endif %}
                                    {% endif %}

                                </div>
                            </div>
                        </div>
                        {% if employer %}
                            <div>
                                <div class="col-md-4 text-left mt-4 mb-4" style="background: #ffffff;">
                                    <a class="btn btn-blue btn-effect mt15 mb15"
                                       href="{% url 'cv:cv_recommended' pk=vacancy.id %}">Соискатели для
                                        Вас</a>
                                </div>

                                <div class="col-md-8 text-right mt-4 mb-4" style="background: #ffffff;">
                                    {% if vacancy.status.code == 'NPB' or vacancy.status.code == 'FRV' %}
                                        <a class="btn btn-blue btn-effect mt15 mb15"
                                           href="{% url 'vacancies:distribute_vacancy' vacancy.id %}">Опубликовать</a>
                                    {% endif %}
                                    <a class="btn btn-blue btn-effect mt15 mb15"
                                       href="{% url 'vacancies:update_vacancy' vacancy.id %}">редактировать</a>
                                    <a class="btn btn-blue btn-effect mt15 mb15"
                                       href="{% url 'vacancies:delete_vacancy' vacancy.id %}">удалить</a>
                                </div>
                            </div>
                        {% else %}
                            <div class="col-md-12 text-right mt-4 mb-4" style="background: #ffffff;">
                                <a class="btn btn-blue btn-effect mt15 mb15"
                                   href="{% url 'vacancies:detail_vacancy' vacancy.id %}">Просмотр</a>
                            </div>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}

{#            {% if employer %}#}
{#                <a class="btn btn-blue btn-effect mt15 mb15" href="{% url 'vacancies:create_vacancy' %}">Создать#}
{#                    вакансию</a>#}
{#            {% endif %}#}
        </div>
    </section>
    <!--    Конец секции МОИ Вакансии-->
{% endblock %}

{% block footer %}
    {% include 'inc_footer.html' %}
{% endblock %}